name: ASM Scan

on:
  schedule:
    - cron: '0 2 * * *'  
  workflow_dispatch:     

permissions:
  contents: read

env:
  DOMAINS: "devops-staging.fly.dev"
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  TELEGRAM_CHAT_ID: "5234453428"

jobs:
  asm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl unzip wget

      - name: Install Subfinder
        run: |
          wget https://github.com/projectdiscovery/subfinder/releases/download/v2.5.7/subfinder_2.5.7_linux_amd64.zip -O subfinder.zip
          unzip -o subfinder.zip
          chmod +x subfinder
          sudo mv subfinder /usr/local/bin/subfinder
          rm subfinder.zip

      - name: Run Subfinder
        run: |
          subfinder -d ${{ env.DOMAINS }} -o subdomains.txt || touch subdomains.txt

      - name: Install httpx
        run: |
          curl -L https://github.com/projectdiscovery/httpx/releases/download/v1.7.1/httpx_1.7.1_linux_amd64.zip -o httpx.zip
          unzip -o httpx.zip
          chmod +x httpx
          sudo mv httpx /usr/local/bin/
          rm httpx.zip

      - name: Validate live hosts using httpx
        run: |
          cat subdomains.txt | httpx -silent -o live_hosts.txt

      - name: Install Nuclei
        run: |
          curl -L https://github.com/projectdiscovery/nuclei/releases/download/v3.4.7/nuclei_3.4.7_linux_amd64.zip -o nuclei.zip
          unzip -o nuclei.zip
          chmod +x nuclei
          sudo mv nuclei /usr/local/bin/nuclei
          rm nuclei.zip

      - name: Run nuclei vulnerability scan on live hosts
        run: |
          nuclei -l live_hosts.txt -o nuclei_results.txt

      - name: Upload scan reports
        uses: actions/upload-artifact@v4
        with:
          name: asm-reports
          path: |
            subdomains.txt
            live_hosts.txt
            nuclei_results.txt

      - name: Send Telegram notification
        if: always()
        run: |
          COUNT=$(wc -l < nuclei_results.txt || echo 0)
          if [ "$COUNT" -gt 0 ]; then
            MSG="Nuclei scan found $COUNT potential vulnerabilities on ${{ env.DOMAINS }}"
          else
            MSG="No vulnerabilities found on ${{ env.DOMAINS }}"
          fi
          curl -s -X POST https://api.telegram.org/bot${{ env.TELEGRAM_BOT_TOKEN }}/sendMessage -d chat_id=${{ env.TELEGRAM_CHAT_ID }} -d text="$MSG"
